### PR TITLE
Release Tool

### PR DESCRIPTION
**Pull request by irq0**
Add tool to help with the release.

Mostly interactive: Show a list of operations to do. Ask the user. Do
the operations.

Features:
- Create release branches
- Create RC tags
- Create release tags
- Sanity checks

Requires a github token. Asked on release start.

The PR also adds pre-command checks for the tool.

Note: Still has rough edges. Written and used for the 0.14.0 release.

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] CHANGELOG.md has been updated should there be relevant changes in this PR.

### CODE REVIEW

**Comment by irq0** [comment]
Uses python rich a lot. Sample output of the sanity-checks command:

```
[2023-04-04T14:43:38Z] ./releasetool.py --state 14.json sanity-checks

                                                  Recent s3gw Quay Tags

  Tag                  Last Mod                    Size        Digest                                               URL
 ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  nightly-latest       2023-04-04 00:45:29+00:00   235839506   sha256:302de7fe7a516678bcddfb0b5f232a63ae33a02804…
  nightly-2023-04-04   2023-04-04 00:45:29+00:00   235839506   sha256:302de7fe7a516678bcddfb0b5f232a63ae33a02804…
  nightly-2023-04-03   2023-04-03 00:45:41+00:00   235739079   sha256:fb0d0f8501a06729197b239449ee8775e3f795ee05…
  nightly-2023-04-02   2023-04-02 00:47:31+00:00   235735951   sha256:999491a8f7ae7ae790446b5c295092941dcea797de…
  nightly-2023-04-01   2023-04-01 00:45:34+00:00   235737404   sha256:c2e2b52c661490198f235ceffd779b1fd3e7837cf6…

URL: https://quay.io/repository/s3gw/s3gw?tab=tags


                                                Recent s3gw-ui Quay Tags

  Tag                    Last Mod                    Size       Digest                                              URL
 ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  latest                 2023-03-30 13:54:46+00:00   62098713   sha256:d756b00397911ef595894ebce7a0898f22fc170b1…
  v0.14.0                2023-03-30 13:54:46+00:00   62098713   sha256:d756b00397911ef595894ebce7a0898f22fc170b1…
  v0.14.0-rc1            2023-03-28 11:40:03+00:00   62098261   sha256:a79fb0b7a4f1df63d6f2e74587400c70b32ff7213…
  v0.14.x-release-test   2023-03-24 11:08:17+00:00   62059684   sha256:7c76d51eda27768b5efcc2b757fcba99170651fcb…
  v0.13.x-release-test   2023-03-24 10:26:14+00:00   62059729   sha256:6178f2b05e1fda856cdbcdbcb35eabc6964fa8316…

URL: https://quay.io/repository/s3gw/s3gw-ui?tab=tags




   Recent ArtifactHub Versions

  Version   TS
 ───────────────────────────────
  0.14.0    2023-03-31 14:16:13
  0.13.0    2023-03-09 16:36:05
  0.12.0    2023-02-16 18:30:51

URL: https://artifacthub.io/packages/helm/s3gw/s3gw




Github Releases


Latest: v0.14.0 tag v0.14.0 created 2023-03-30 13:49:15


Release Notes


main s3gw-v0.14.0.md latest link ok
main v0.14.0 in release note ok
v0.14.0 s3gw-v0.14.0.md latest link ok
v0.14.0 v0.14.0 in release note ok
```

**Comment by giubacc** [comment]
I will use/test this with the next `0.15.0` release.
I suggest to set this for `0.16.0` so we can have a full test coverage with `0.15.0`.

**Comment by giubacc** [comment]
I'm trying to start using the tool, but I'm immediately having a blocker:

```
./releasetool.py --state v0.15 start --s3gw s3gw --s3gw-ceph ceph --s3gw-ui s3gw-ui --s3gw-charts s3gw-charts --github-token XXXXXXXXXXXXX

Hello Giuseppe Baccini
New version MAJOR.MINOR? (0.15): 0.15
New version PATCH? (0): 0
Traceback (most recent call last):
  File "/home/giuseppe/developer/release/./releasetool.py", line 699, in <module>
    release(obj={})
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/giuseppe/developer/release/./releasetool.py", line 211, in start
    branch_name = GitBranchName(f"s3gw-v{ctx.obj['version']}")
KeyError: 'version'
```

**Comment by irq0** [comment]
> I'm trying to start using the tool, but I'm immediately having a blocker:
> 

Sorry about that. Should be easy to fix on the go though. There may be similar bugs from a bit of refactoring.

**Comment by giubacc** [comment]
> > I'm trying to start using the tool, but I'm immediately having a blocker:
> 
> Sorry about that. Should be easy to fix on the go though. There may be similar bugs from a bit of refactoring.

Don't worry, dunno if this is something related to my env; if you need me to do some test, do not hesitate to ask.

**Comment by irq0** [comment]
> > > I'm trying to start using the tool, but I'm immediately having a blocker:
> > 
> > 
> > Sorry about that. Should be easy to fix on the go though. There may be similar bugs from a bit of refactoring.
> 
> Don't worry, dunno if this is something related to my env; if you need me to do some test, do not hesitate to ask.

Last push should fix the bug you already saw and adds a couple of libs to the requirements.txt.

The tool assumes that you did all steps with it. Since you already branched you would need to set the state in the json file manually to reflect where you are in the process. I understand if you rather get on with the process ;)

If you do actually want to toy around with this: The `ctx.obj` dict and the asserts at the beginning of the click functions tell what to set :).

**Comment by giubacc** [comment]
I haven't had the chance to try properly this last time but I think we can merge it and try to enhance the tool by little steps if/when needed.

**Review by giubacc — APPROVED** [review]

**Comment by irq0** [comment]
sounds good!

**Pull request merged**
