### PR TITLE
Add Shellcheck Pre Commit Hook

### PR DESCRIPTION
**Pull request by irq0**
Add Shellcheck to Pre Commit Hooks

See: https://github.com/koalaman/shellcheck

### CODE REVIEW

**Review by m-ildefons — APPROVED** [review]
LGTM

**Comment by irq0** [comment]
No idea why nightly builds trigger, but I don't think they are relevant here

**Comment by m-ildefons** [comment]
Nightlies trigger because you changed them.

**Comment by jecluis** [comment]
And the nightly fails because of secrets. Good to ignore I think.

**Pull request merged**
