### PR TITLE
docs, build: drop mention of s3gw-core, fix standalone run, use GCC 12 in Dockerfile.build-radosgw

### PR DESCRIPTION
**Pull request by tserong**
# Describe your changes

Bit of docs cleanup

## Issue ticket number and link

https://github.com/aquarist-labs/s3gw/issues/651

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] CHANGELOG.md has been updated should there be relevant changes in this PR.

### CODE REVIEW

**Comment by tserong** [comment]
(Possibly the developer docs should say to use the top-level Dockerfile now that that exists, rather than the split out ones, but at least with this change you _can_ follow the developer docs and have it actually work)

**Review by jecluis — DISMISSED** [review]

**Comment by tserong** [comment]
Wait a minute, I found another couple of references to dbstore I need to get rid of...

**Comment by tserong** [comment]
Alright, that should do it.

**Comment by tserong** [comment]
Alright, that should _really_ do it.

**Review by jecluis — APPROVED** [review]

**Pull request merged**
