### PR TITLE
s3gw: release v0.16.0

### PR DESCRIPTION
**Pull request by jecluis**
Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

### CODE REVIEW

**Review by 0xavi0 — APPROVED** [review]
lgtm

**Comment by jecluis** [comment]
@m-ildefons can you take a look at what is happening with the quay login?

**Comment by m-ildefons** [comment]
You can't access GH secrets with PRs from forks. Either create a branch on the repo itself and PR from there or just push to release branch (carefully ;-))
While it's of course nice to have someone else look at the release notes, there's questionable benefit to doing PR reviews for release commits anyways IMO.

**Comment by jecluis** [comment]
> You can't access GH secrets with PRs from forks.

Ah, yeah. I forgot :sweat_smile: 

> While it's of course nice to have someone else look at the release notes, there's questionable benefit to doing PR reviews for release commits anyways IMO.

No disagreement there.

**Comment by jecluis** [comment]
> You can't access GH secrets with PRs from forks.
Ah, yeah. I forgot :sweat_smile: 

> While it's of course nice to have someone else look at the release notes, there's questionable benefit to doing PR reviews for release commits anyways IMO.

No disagreement there.

**Pull request closed without merging**
