### PR TITLE
s3tr enhancements

### LINKED ISSUE #665: ci: s3 tests - switch build fail decision from "shall pass" list to "ok to fail" list
What we have: A s3-tests.txt containing a list of s3 tests that must pass for the test runner to succeed.

What we rather have: A list of tests that are ok to fail. With test names, excuses, links to issues.

Side effect: It would mean that new s3 tests must automatically pass. It would poke us right away if something new comes in.

The list: The "ok to fail list" would be 90 instead of > 200 lines. The 90 will come down over time and make it very reasonable to have an excuse or reference to a ticket in the file.

Options:
Make list JSON so $tool we don't have can help with removing those lines later or display proper links to issues on a dashboard.
Ideally every listed test has a linked issue why it is failing or why we don't support this feature.

### PR DESCRIPTION
**Pull request by irq0**
Collection of s3tr enhancements:

- Collect prometheus metrics after test
- Selectively enable lifecycle debugging mode (reduces logs)
- Change "this tests shall pass" mode to "ok to fail"

Merge must be coordinated with CI change to aquarist-labs/ceph and merge of an excuse.csv file there

Fixes: https://github.com/aquarist-labs/s3gw/issues/665

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] CHANGELOG.md has been updated should there be relevant changes in this PR.

### CODE REVIEW

**Review by m-ildefons — APPROVED** [review]
LGTM

**Comment by jecluis** [comment]
@irq0 is this good to go?

**Comment by irq0** [comment]
> @irq0 is this good to go?

Merge needs coordination with https://github.com/aquarist-labs/ceph/pull/221 to not break CI on aquarist-labs/ceph

**Comment by jecluis** [comment]
Okay. Both are approved now. Merge away.

**Pull request merged**
