### PR TITLE
ci: nightly UI builds

### LINKED ISSUE #663: CI: Nightly builds for the UI
### What needs to be done

- [ ] Build a UI container on a nightly schedule.
- [ ] Run UI test suite against nightly container and collect results
- [ ] Ensure nightly containers are cleaned from the registry after a while (e.g. a week) 

### Why it needs to be done

Better testing coverage, faster turn around times, helps in the development of the UI

### Acceptance Criteria

See above

### Additional Information

See nightly builds for the s3gw container for reference

### PR DESCRIPTION
**Pull request by m-ildefons**
Add nightly builds for UI container

Requires: aquarist-labs/s3gw-ui#250
Fixes: #663

- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [x] CHANGELOG.md has been updated should there be relevant changes in this PR.

### CODE REVIEW

**Review by callithea — APPROVED** [review]
Lgtm :)

**Comment by jecluis** [comment]
We have a checks failure preventing merging this PR. @m-ildefons is this something easily addressable? If not, we'll push this past v0.23.0.

**Comment by m-ildefons** [comment]
The fail is expected since this is a PR from a fork and doesn't have access to the quay.io login credentials as a result. I should have opened this as a PR from a branch within the same repo :roll_eyes:

**Comment by m-ildefons** [comment]
See --> https://github.com/aquarist-labs/s3gw/pull/780

**Pull request closed without merging**
