### PR TITLE
Improved Doc for docker-compose and secrets

### PR DESCRIPTION
**Pull request by filopedraz**
### Description

- Improved doc to include `docker-compose`
- Included reference on how to set default secrets
- Fixed `docker-compose` and removed proxy.

### CODE REVIEW

**Review by jecluis — COMMENTED** [review]
lgtm - @m-ildefons mind taking a look to confirm?

**Comment by jecluis** [comment]
@filopedraz Thanks for the submission. For us to be able to merge your contribution, we'll need you to provide the commit with a DCO (see https://wiki.linuxfoundation.org/dco ). This can come in the form of adding a `Signed-off-by: Your Name <your@email.tld>` in the commit message.

**Comment by filopedraz** [comment]
I tried to run the `docker-compose` but it didn't work. Some issues with the proxy and an env variable wrongly passed. I updated the description above. You can check my last commit as well.

**Comment by jecluis** [comment]
@filopedraz thanks for the DCO on your latest commit. Unfortunately you'll need to sign-off all the commits. May I suggest a clean branch, cherry-pick individual commits, run a `git commit --amend` on each, and add the `Signed-off-by:`? That might be the easiest approach given the small number of commits involved in this patch set.

**Comment by jecluis** [comment]
Also, linting the `docker-compose.yaml` file has failed. Please consider the following error:

```
Run pre-commit run --show-diff-on-failure --color=always --files README.md docker-compose.yaml
  pre-commit run --show-diff-on-failure --color=always --files README.md docker-compose.yaml
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
trim trailing whitespace....................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook
```

on lines

```
diff --git a/docker-compose.yaml b/docker-compose.yaml
index 8a3187c..73ffe50 100644
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -22,6 +22,6 @@ services:
       - "8080:8080"
     environment:
       S3GW_SERVICE_URL: "http://s3gw:7480"
-      
+
 volumes:
   data:
Error: Process completed with exit code 1.
```

If you happen to install the pre-commit hook available on the repository, you may be able to verify whether the problem is fixed by running `pre-commit run check-yaml --file docker-compose.yaml`.

**Pull request closed without merging**
