### PR TITLE
ADR: SFS Design

### PR DESCRIPTION
**Pull request by irq0**
ADRs distilled from the Conflu page and notes.

Previous discussion:
https://github.com/aquarist-labs/s3gw-tools/pull/112

### CODE REVIEW

**Review by jhmarina — CHANGES_REQUESTED** [review]
lgtm but I think you'll need to rename the files, since there's already an ADR starting by `0001`: https://github.com/aquarist-labs/s3gw/blob/main/docs/decisions/0001-reorganize-documentation.md

**Comment by irq0** [comment]
Renamed the files. ADR number +=1.

**Review by jhmarina — DISMISSED** [review]
thanks for the changes @irq0

**Comment by jhmarina** [comment]
@irq0 could you sign off all commits to keep the bot happy? :)

**Review by jhmarina — APPROVED** [review]

**Pull request merged**
