### PR TITLE
Add decision about versioning of the UI REST API

### PR DESCRIPTION
**Pull request by votdev**
# Describe your changes

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] CHANGELOG.md has been updated should there be relevant changes in this PR.

### CODE REVIEW

**Review by jecluis — DISMISSED** [review]
sounds good to me.

**Comment by irq0** [comment]
What if a browser has the UI open with all the javascript loaded and the backend restarts to a new version. Will the UI app be able to detect that without any versioning information?

**Comment by jecluis** [comment]
> What if a browser has the UI open with all the javascript loaded and the backend restarts to a new version. Will the UI app be able to detect that without any versioning information?

That can be prevented with a version check, but doesn't necessarily mean maintaining API versions. One can increase the API version if things change or are incompatible, and share it with the UI as an HTTP header or something, and then have the UI check whether that's the version it knows -- if not, ask the user to refresh.

I think the change to the ADR still makes sense though, it makes little sense to introduce proper API versioning IMO.

**Review by irq0 — DISMISSED** [review]
sgtm

Unimportant nit: Haven't seen 'S3gw' before, only 'S3GW' or 's3gw'

**Comment by votdev** [comment]
> Unimportant nit: Haven't seen 'S3gw' before, only 'S3GW' or 's3gw'

That's the result of using camel-case. I've changed it to `S3GW-Foo-Bar`.

BTW, using the `X-` prefix in custom headers is [deprecated](https://www.rfc-editor.org/rfc/rfc6648).

**Comment by jecluis** [comment]
lgtm

**Review by jecluis — APPROVED** [review]

**Pull request merged**
